/*
 *  SCPluginUtilities.m
 *  Sensible TableView
 *  Version: 5.4.0
 *
 *
 *	THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY UNITED STATES
 *	INTELLECTUAL PROPERTY LAW AND INTERNATIONAL TREATIES. UNAUTHORIZED REPRODUCTION OR
 *	DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES. YOU SHALL NOT DEVELOP NOR
 *	MAKE AVAILABLE ANY WORK THAT COMPETES WITH A SENSIBLE COCOA PRODUCT DERIVED FROM THIS
 *	SOURCE CODE. THIS SOURCE CODE MAY NOT BE RESOLD OR REDISTRIBUTED ON A STAND ALONE BASIS.
 *
 *	USAGE OF THIS SOURCE CODE IS BOUND BY THE LICENSE AGREEMENT PROVIDED WITH THE
 *	DOWNLOADED PRODUCT.
 *
 *  Copyright 2011-2015 Sensible Cocoa. All rights reserved.
 *
 *
 *	This notice may not be removed from this file.
 *
 */


#import "SCPluginUtilities.h"

#import "SCGlobals.h"
#import "SCDataStore.h"


@implementation SCPluginUtilities

+ (id)objectForPluginDictionary:(NSDictionary *)pluginDictionary
{
    NSString *customClassName = [pluginDictionary valueForKey:kCustomClassName];
    Class CustomClass = NSClassFromString(customClassName);
    if(!CustomClass)
    {
        if(customClassName)
        {
            if([customClassName isEqualToString:@"SCEntityDefinition"])
            {
                SCDebugLog(@"Warning: Your Storyboard configuration requires the 'STVCoreData' framework to be added to your project. Either add the aforementioned framework or remove the '%@' component from your Storyboard.", customClassName);
                
                SCMissingFrameworkDataDefinition *missingFrameworkDefinition = [[SCMissingFrameworkDataDefinition alloc] init];
                [missingFrameworkDefinition setValue:[pluginDictionary valueForKey:kibUniqueID] forKey:kibUniqueID];
                missingFrameworkDefinition.missingFrameworkMessage = @"Project missing STVCoreData framework";
                return missingFrameworkDefinition;
            }
            
            if([customClassName isEqualToString:@"SCWebServiceDefinition"])
            {
                SCDebugLog(@"Warning: Your Storyboard configuration requires the 'STVWebServices' framework to be added to your project. Either add the aforementioned framework or remove the '%@' component from your Storyboard.", customClassName);
                
                SCMissingFrameworkDataDefinition *missingFrameworkDefinition = [[SCMissingFrameworkDataDefinition alloc] init];
                [missingFrameworkDefinition setValue:[pluginDictionary valueForKey:kibUniqueID] forKey:kibUniqueID];
                missingFrameworkDefinition.missingFrameworkMessage = @"Project missing STVWebServices framework";
                return missingFrameworkDefinition;
            }
            
            if([customClassName isEqualToString:@"SCParseDefinition"])
            {
                SCDebugLog(@"Warning: Your Storyboard configuration requires the 'STVParse' framework to be added to your project. Either add the aforementioned framework or remove the '%@' component from your Storyboard.", customClassName);
                
                SCMissingFrameworkDataDefinition *missingFrameworkDefinition = [[SCMissingFrameworkDataDefinition alloc] init];
                [missingFrameworkDefinition setValue:[pluginDictionary valueForKey:kibUniqueID] forKey:kibUniqueID];
                missingFrameworkDefinition.missingFrameworkMessage = @"Project missing STVParse framework";
                return missingFrameworkDefinition;
            }
                
            if([customClassName isEqualToString:@"SCiCloudKeyValueDefinition"])
            {
                SCDebugLog(@"Warning: Your Storyboard configuration requires the 'STViCloud' framework to be added to your project. Either add the aforementioned framework or remove the '%@' component from your Storyboard.", customClassName);
                
                SCMissingFrameworkDataDefinition *missingFrameworkDefinition = [[SCMissingFrameworkDataDefinition alloc] init];
                [missingFrameworkDefinition setValue:[pluginDictionary valueForKey:kibUniqueID] forKey:kibUniqueID];
                missingFrameworkDefinition.missingFrameworkMessage = @"Project missing STViCloud framework";
                return missingFrameworkDefinition;
            }
            
            //else
            SCDebugLog(@"Warning: class '%@' generated by Interface Builder is not supported by your current installed STV framework(s). Make sure the correct STV framework is included in your project before using this class.", customClassName);
        }
        
        return nil;
    }
    
    NSMutableDictionary *ibDictionary = [NSMutableDictionary dictionaryWithDictionary:pluginDictionary];
    [ibDictionary removeObjectForKey:kCustomClassName];
    
    id object;
    if([CustomClass conformsToProtocol:@protocol(SCibInitialization)])
    {
        object = [[CustomClass alloc] initWithibDictionary:ibDictionary];
    }
    else
    {
        object = [[CustomClass alloc] init];
        for(NSString *key in pluginDictionary.allKeys)
        {
            [object setValue:[pluginDictionary valueForKey:key] forKey:key];
        }
    }
    
    return object;
}

@end




